//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPS_NotePad.Resources.Resx {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPS_NotePad.Resources.Resx.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Pin.
        /// </summary>
        internal static string AddPin {
            get {
                return ResourceManager.GetString("AddPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add photo .
        /// </summary>
        internal static string AddPin2 {
            get {
                return ResourceManager.GetString("AddPin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All fields must be filled.
        /// </summary>
        internal static string Alert_All_Field {
            get {
                return ResourceManager.GetString("Alert_All_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error! Geo location disable. Restart the application.
        /// </summary>
        internal static string Alert_Device_GeoLocacia {
            get {
                return ResourceManager.GetString("Alert_Device_GeoLocacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error! No connection to the internet. Restart the application.
        /// </summary>
        internal static string Alert_Device_Internet {
            get {
                return ResourceManager.GetString("Alert_Device_Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email already exist.
        /// </summary>
        internal static string Alert_Email1 {
            get {
                return ResourceManager.GetString("Alert_Email1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email do not exist.
        /// </summary>
        internal static string Alert_Email2 {
            get {
                return ResourceManager.GetString("Alert_Email2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email is not valid.
        /// </summary>
        internal static string Alert_Email3 {
            get {
                return ResourceManager.GetString("Alert_Email3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK! Are you registered..
        /// </summary>
        internal static string Alert_Ok_Reg {
            get {
                return ResourceManager.GetString("Alert_Ok_Reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password do not exist.
        /// </summary>
        internal static string Alert_Password1 {
            get {
                return ResourceManager.GetString("Alert_Password1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password must have from 8 to 16 symbols, A - Z, a - z, 1 - 9. 
        ///Password must contain at least one capital letter, one lowercase letter and one number.
        /// </summary>
        internal static string Alert_Password2 {
            get {
                return ResourceManager.GetString("Alert_Password2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Must be 0.0000 or -0.0000.
        /// </summary>
        internal static string Alert_Position {
            get {
                return ResourceManager.GetString("Alert_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error saved data.
        /// </summary>
        internal static string Alert_SavePin {
            get {
                return ResourceManager.GetString("Alert_SavePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A-Z, a-z symbols only.
        /// </summary>
        internal static string Alert_Search {
            get {
                return ResourceManager.GetString("Alert_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arrival.
        /// </summary>
        internal static string arrival {
            get {
                return ResourceManager.GetString("arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Camera.
        /// </summary>
        internal static string Button_Camera {
            get {
                return ResourceManager.GetString("Button_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Galery.
        /// </summary>
        internal static string Button_Galery {
            get {
                return ResourceManager.GetString("Button_Galery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Label.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm password.
        /// </summary>
        internal static string Confirmpassword {
            get {
                return ResourceManager.GetString("Confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Coordinates.
        /// </summary>
        internal static string Coordinates {
            get {
                return ResourceManager.GetString("Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create account.
        /// </summary>
        internal static string Createaccount {
            get {
                return ResourceManager.GetString("Createaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Departure.
        /// </summary>
        internal static string departure {
            get {
                return ResourceManager.GetString("departure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        internal static string EditItem {
            get {
                return ResourceManager.GetString("EditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Pickup.
        /// </summary>
        internal static string EnterPickup {
            get {
                return ResourceManager.GetString("EnterPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Origin route should be different than destination route.
        /// </summary>
        internal static string ErrorRoute {
            get {
                return ResourceManager.GetString("ErrorRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email. Must have - aaa@aa.aa.
        /// </summary>
        internal static string ErrorText_Email {
            get {
                return ResourceManager.GetString("ErrorText_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Must have 2-16 symbols.
        /// </summary>
        internal static string ErrorText_Name {
            get {
                return ResourceManager.GetString("ErrorText_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8-16 symbols first capital letter, one lowercase letter, one digit.
        /// </summary>
        internal static string ErrorText_Password {
            get {
                return ResourceManager.GetString("ErrorText_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Foto.
        /// </summary>
        internal static string Foto {
            get {
                return ResourceManager.GetString("Foto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose a language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Latitude.
        /// </summary>
        internal static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Location.
        /// </summary>
        internal static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log  in.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Longitude.
        /// </summary>
        internal static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Map.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete is .
        /// </summary>
        internal static string Message_Delete {
            get {
                return ResourceManager.GetString("Message_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please turn on GPS for the proper working of the application.
        /// </summary>
        internal static string NoGPSConnection {
            get {
                return ResourceManager.GetString("NoGPSConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No route found.
        /// </summary>
        internal static string NoRouteFound {
            get {
                return ResourceManager.GetString("NoRouteFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pins.
        /// </summary>
        internal static string Pins {
            get {
                return ResourceManager.GetString("Pins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        internal static string PlaceholderEmail {
            get {
                return ResourceManager.GetString("PlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input the label.
        /// </summary>
        internal static string PlaceholderEntryAddPin1 {
            get {
                return ResourceManager.GetString("PlaceholderEntryAddPin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input the description.
        /// </summary>
        internal static string PlaceholderEntryAddPin2 {
            get {
                return ResourceManager.GetString("PlaceholderEntryAddPin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string PlaceholderName {
            get {
                return ResourceManager.GetString("PlaceholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password confirm.
        /// </summary>
        internal static string PlaceholderPassConfirm {
            get {
                return ResourceManager.GetString("PlaceholderPassConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        internal static string PlaceholderPassword {
            get {
                return ResourceManager.GetString("PlaceholderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search of pins.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Route.
        /// </summary>
        internal static string SearchGooglePlaces {
            get {
                return ResourceManager.GetString("SearchGooglePlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop route.
        /// </summary>
        internal static string StopRoute {
            get {
                return ResourceManager.GetString("StopRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Where to.
        /// </summary>
        internal static string WhereTo {
            get {
                return ResourceManager.GetString("WhereTo", resourceCulture);
            }
        }
    }
}
